from fastapi import APIRouter, Depends, HTTPException, Response
from pydantic import BaseModel
from typing import Optional
from utils.dependencies import get_current_user
from database import get_db
from bson import ObjectId
from datetime import datetime
import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

router = APIRouter()

class ReportRequest(BaseModel):
    conversation_id: Optional[str] = None

@router.post("/reports")
async def generate_report(request: ReportRequest, current_user: dict = Depends(get_current_user)):
    db = get_db()
    
    # Fetch conversation
    if request.conversation_id:
        conversation = await db.Conversations.find_one({"_id": ObjectId(request.conversation_id), "user_id": current_user["id"]})
    else:
        # Get latest conversation
        conversation = await db.Conversations.find_one({"user_id": current_user["id"]}, sort=[("created_at", -1)])
        
    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")
        
    conversation_id = str(conversation["_id"])
    
    messages = conversation.get("messages", [])
    user_name = current_user.get("name", "User")
    date_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    
    # Generate PDF
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    Story = []
    
    title_style = styles['Heading1']
    title_style.alignment = TA_CENTER
    
    Story.append(Paragraph("MediAssist AI - Medical Report", title_style))
    Story.append(Spacer(1, 0.2 * 72))
    
    Story.append(Paragraph(f"<b>Patient Name:</b> {user_name}", styles['Normal']))
    Story.append(Paragraph(f"<b>Date:</b> {date_str}", styles['Normal']))
    Story.append(Spacer(1, 0.2 * 72))
    
    Story.append(Paragraph("<b>Disclaimer:</b> This report is generated by an AI assistant for educational purposes only. It is NOT a medical diagnosis. Please consult a qualified healthcare professional.", styles['Normal']))
    Story.append(Spacer(1, 0.2 * 72))
    
    Story.append(Paragraph("<b>Conversation Summary:</b>", styles['Heading2']))
    Story.append(Spacer(1, 0.1 * 72))
    
    for msg in messages:
        role = "You" if msg.get("role") == "user" else "MediAssist"
        content = msg.get("content", "")
        # Basic escaping to avoid reportlab xml errors
        content = content.replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")
        Story.append(Paragraph(f"<b>{role}:</b> {content}", styles['Normal']))
        Story.append(Spacer(1, 0.1 * 72))
        
    doc.build(Story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    # Save report metadata and binary in DB
    report_record = {
        "user_id": current_user["id"],
        "conversation_id": conversation_id,
        "title": f"Report - {date_str}",
        "created_at": datetime.utcnow(),
        "pdf_data": pdf_bytes
    }
    
    result = await db.Reports.insert_one(report_record)
    
    # Return PDF blob
    return Response(content=pdf_bytes, media_type="application/pdf")


@router.get("/reports")
async def list_reports(current_user: dict = Depends(get_current_user)):
    db = get_db()
    cursor = db.Reports.find({"user_id": current_user["id"]}, {"pdf_data": 0}).sort("created_at", -1)
    reports = await cursor.to_list(length=100)
    
    for r in reports:
        r["id"] = str(r["_id"])
        del r["_id"]
        if "conversation_id" in r:
            r["conversation_id"] = str(r["conversation_id"])
            
    return {"reports": reports}


@router.get("/reports/{report_id}/download")
async def download_report(report_id: str, current_user: dict = Depends(get_current_user)):
    db = get_db()
    report = await db.Reports.find_one({"_id": ObjectId(report_id), "user_id": current_user["id"]})
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
        
    return Response(content=report["pdf_data"], media_type="application/pdf")
