import { ArrowRight, BotMessageSquare, CheckCircle2, ChevronRight, HeartHandshake, HeartPulse, ImagePlus, LockKeyhole, MapPinned, Mic, ShieldCheck, Sparkles, Stethoscope } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";

const features = [
  { icon: BotMessageSquare, title: "Thoughtful symptom conversations", copy: "Share what you are experiencing and receive clear, cautious educational guidance." },
  { icon: Mic, title: "Speak naturally", copy: "Use a voice consultation when typing is inconvenient, with a transcript you can review." },
  { icon: ImagePlus, title: "Understand visible concerns", copy: "Upload a skin, eye, swelling, or minor-wound image for a descriptive AI assessment." },
  { icon: MapPinned, title: "Find care nearby", copy: "Use your location to find nearby hospitals, clinics, and emergency facilities." },
];

const principles = [
  "Never presents an AI response as a confirmed diagnosis",
  "Flags urgent symptoms and directs you to immediate care",
  "Explains uncertainty, possible conditions, and sensible next steps",
];

export function LandingPage() {
  return (
    <div className="min-h-screen overflow-x-hidden bg-white text-slate-900 dark:bg-slate-950 dark:text-white">
      <header className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/" className="flex items-center gap-2.5 font-bold tracking-tight"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-sky-400 to-sky-600 text-white shadow-glow"><HeartPulse className="h-5 w-5" /></span><span className="text-lg">Medi<span className="text-sky-500">Assist</span> <span className="text-slate-400">AI</span></span></Link><nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 dark:text-slate-300 md:flex"><a href="#how-it-works" className="transition hover:text-sky-600">How it works</a><a href="#safety" className="transition hover:text-sky-600">Safety first</a><a href="#features" className="transition hover:text-sky-600">Features</a></nav><div className="flex items-center gap-2 sm:gap-3"><Link to="/login"><Button variant="outline" size="sm">Log in</Button></Link><Link to="/signup"><Button size="sm">Get started <ArrowRight className="h-4 w-4" /></Button></Link></div></header>

      <main>
        <section className="relative isolate"><div className="absolute inset-x-0 top-0 -z-10 h-[600px] overflow-hidden"><div className="absolute left-1/2 top-[-380px] h-[720px] w-[720px] -translate-x-1/2 rounded-full bg-sky-200/50 blur-3xl dark:bg-sky-500/10" /><div className="absolute right-[-120px] top-24 h-72 w-72 rounded-full bg-emerald-100/60 blur-3xl dark:bg-emerald-500/10" /></div><div className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-16 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pb-32 lg:pt-24"><div className="max-w-2xl animate-fade-up"><div className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-white/80 px-3 py-1.5 text-xs font-bold text-sky-700 shadow-sm backdrop-blur dark:border-sky-900 dark:bg-slate-900/80 dark:text-sky-300"><Sparkles className="h-3.5 w-3.5" />A calmer way to navigate health questions</div><h1 className="mt-6 text-4xl font-bold leading-[1.08] tracking-tight text-slate-950 dark:text-white sm:text-5xl lg:text-6xl">Health guidance that helps you decide <span className="text-sky-500">what to do next.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-300 sm:text-lg">MediAssist AI brings text, voice, and image-based health conversations into one private, easy-to-use space—always educational, never a substitute for a clinician.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/signup"><Button size="lg">Start a consultation <ArrowRight className="h-4 w-4" /></Button></Link><Link to="/login"><Button variant="outline" size="lg">Log in</Button></Link><a href="#how-it-works"><Button variant="outline" size="lg">See how it works <ChevronRight className="h-4 w-4" /></Button></a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-medium text-slate-500 dark:text-slate-400"><span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-4 w-4 text-emerald-500" />Designed around caution</span><span className="inline-flex items-center gap-1.5"><LockKeyhole className="h-4 w-4 text-emerald-500" />Your data stays protected</span></div></div>
          <div className="relative mx-auto w-full max-w-lg animate-fade-up [animation-delay:120ms]"><div className="absolute -inset-5 -z-10 rounded-[2.5rem] bg-gradient-to-br from-sky-100 to-emerald-100 blur-2xl dark:from-sky-500/15 dark:to-emerald-500/10" /><Card className="overflow-hidden border-white/70 bg-white/90 p-0 shadow-2xl shadow-sky-900/10 backdrop-blur dark:border-slate-800 dark:bg-slate-900/90"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-sky-100 text-sky-600 dark:bg-sky-500/15 dark:text-sky-300"><HeartPulse className="h-4 w-4" /></span><div><p className="text-xs font-bold text-slate-800 dark:text-white">MediAssist conversation</p><p className="text-[11px] text-emerald-600 dark:text-emerald-400">● Ready to listen</p></div></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-500 dark:bg-slate-800">Educational only</span></div><div className="space-y-4 p-5"><div className="max-w-[85%] rounded-2xl rounded-tl-sm bg-slate-100 px-4 py-3 text-sm leading-6 text-slate-700 dark:bg-slate-800 dark:text-slate-200">I’ve had a sore throat and fever for two days. What should I watch for?</div><div className="ml-auto max-w-[92%] rounded-2xl rounded-tr-sm bg-sky-500 px-4 py-3 text-sm leading-6 text-white">I can help you think through this. A few details can help: your temperature, any cough or trouble breathing, and whether symptoms are getting worse.</div><div className="rounded-2xl border border-sky-100 bg-sky-50 p-3.5 dark:border-sky-900/70 dark:bg-sky-950/30"><div className="flex items-center gap-2 text-xs font-bold text-sky-800 dark:text-sky-200"><Stethoscope className="h-4 w-4" />How MediAssist responds</div><div className="mt-2 grid grid-cols-3 gap-2 text-center text-[10px] font-semibold text-slate-600 dark:text-slate-300"><span className="rounded-lg bg-white px-1 py-2 dark:bg-slate-900">Ask follow-ups</span><span className="rounded-lg bg-white px-1 py-2 dark:bg-slate-900">Explain urgency</span><span className="rounded-lg bg-white px-1 py-2 dark:bg-slate-900">Suggest next steps</span></div></div></div></Card><div className="absolute -bottom-7 -left-7 hidden rounded-2xl border border-white bg-white p-3 shadow-lg dark:border-slate-700 dark:bg-slate-900 sm:flex sm:items-center sm:gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-100 text-emerald-600 dark:bg-emerald-500/15 dark:text-emerald-300"><MapPinned className="h-4 w-4" /></span><div><p className="text-xs font-bold">Care when it matters</p><p className="text-[11px] text-slate-500">Nearby hospital finder</p></div></div></div></div></section>

        <section id="how-it-works" className="border-y border-slate-100 bg-slate-50 py-20 dark:border-slate-800 dark:bg-slate-900/40"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-sky-600">Built for the next right step</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Clear support in three simple moments.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[{ number: "01", title: "Share what’s going on", copy: "Type, speak, or upload an image of a visible concern.", icon: HeartHandshake }, { number: "02", title: "Understand the picture", copy: "Get possible explanations, relevant follow-up questions, and a clear urgency signal.", icon: Sparkles }, { number: "03", title: "Choose the next step", copy: "Use guidance for home care, scheduling care, or finding a nearby hospital.", icon: MapPinned }].map((step) => <div key={step.number} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center justify-between"><span className="text-sm font-bold text-sky-500">{step.number}</span><step.icon className="h-5 w-5 text-emerald-500" /></div><h3 className="mt-8 text-lg font-bold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{step.copy}</p></div>)}</div></div></section>

        <section id="features" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-600">One connected health space</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Meet people where they are.</h2></div><div className="flex flex-wrap items-center gap-4"><Link to="/login" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-sky-700 dark:text-slate-300">Log in</Link><Link to="/signup" className="inline-flex items-center gap-2 text-sm font-bold text-sky-600 hover:text-sky-700">Explore MediAssist <ArrowRight className="h-4 w-4" /></Link></div></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map((feature) => <Card key={feature.title} className="group p-6 transition hover:-translate-y-1 hover:border-sky-200 hover:shadow-lg dark:hover:border-sky-900"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-sky-100 text-sky-600 transition group-hover:bg-sky-500 group-hover:text-white dark:bg-sky-500/15 dark:text-sky-300"><feature.icon className="h-5 w-5" /></span><h3 className="mt-5 font-bold">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{feature.copy}</p></Card>)}</div></section>

        <section id="safety" className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-10 text-white sm:px-10 lg:grid lg:grid-cols-[1fr_.9fr] lg:items-center lg:gap-12 lg:px-14 lg:py-14"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold text-sky-200"><ShieldCheck className="h-3.5 w-3.5" />Safety is not an afterthought</span><h2 className="mt-5 text-3xl font-bold tracking-tight sm:text-4xl">Helpful does not mean overconfident.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300 sm:text-base">MediAssist is designed to communicate uncertainty and make escalation easy. It cannot diagnose, replace a clinician, or provide emergency services.</p><Link to="/about" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-sky-300 hover:text-white">Read our approach <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-8 space-y-4 rounded-2xl border border-white/10 bg-white/5 p-5 lg:mt-0">{principles.map((principle) => <div key={principle} className="flex gap-3 text-sm leading-6 text-slate-200"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />{principle}</div>)}</div></div></section>
      </main>
      <footer className="border-t border-slate-100 px-5 py-8 text-center text-xs text-slate-500 dark:border-slate-800 dark:text-slate-400">© {new Date().getFullYear()} MediAssist AI · Informational health support, not medical diagnosis or emergency care.</footer>
    </div>
  );
}
