import { useState, useEffect } from 'react';
import api from '../lib/api';
import { useAuthStore } from '../store/useStore';
import { User, Activity, Loader2, Save, FileText } from 'lucide-react';
import jsPDF from 'jspdf';

const Profile = () => {
  const { user, updateUser } = useAuthStore();
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState({ text: '', type: '' });
  
  const [medicalHistory, setMedicalHistory] = useState({
    blood_group: '',
    known_allergies: '',
    chronic_diseases: '',
    emergency_contact: '',
    age: '',
    gender: ''
  });

  useEffect(() => {
    fetchProfile();
  }, []);

  const fetchProfile = async () => {
    setLoading(true);
    try {
      const response = await api.get('/profile');
      updateUser(response.data);
      const mh = response.data.medical_history;
      setMedicalHistory({
        blood_group: mh?.blood_group || '',
        known_allergies: mh?.known_allergies?.join(', ') || '',
        chronic_diseases: mh?.chronic_diseases?.join(', ') || '',
        emergency_contact: mh?.emergency_contact || '',
        age: mh?.age?.toString() || '',
        gender: mh?.gender || ''
      });
    } catch (error) {
      console.error("Failed to load profile");
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setMessage({ text: '', type: '' });
    
    try {
      const dataToSave = {
        blood_group: medicalHistory.blood_group,
        known_allergies: medicalHistory.known_allergies.split(',').map(s => s.trim()).filter(Boolean),
        chronic_diseases: medicalHistory.chronic_diseases.split(',').map(s => s.trim()).filter(Boolean),
        emergency_contact: medicalHistory.emergency_contact,
        age: medicalHistory.age ? parseInt(medicalHistory.age) : null,
        gender: medicalHistory.gender
      };
      
      const response = await api.put('/profile', dataToSave);
      updateUser(response.data);
      setMessage({ text: 'Profile updated successfully!', type: 'success' });
    } catch (error) {
      setMessage({ text: 'Failed to update profile.', type: 'error' });
    } finally {
      setSaving(false);
    }
  };

  const generateReport = () => {
    const doc = new jsPDF();
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(14, 165, 233);
    doc.text("MediAssist AI - Health Report", 20, 20);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 30);
    
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(`Patient Name: ${user?.name}`, 20, 45);
    doc.text(`Email: ${user?.email}`, 20, 52);
    doc.text(`Age: ${medicalHistory.age || 'N/A'}`, 20, 59);
    doc.text(`Gender: ${medicalHistory.gender || 'N/A'}`, 20, 66);
    doc.text(`Blood Group: ${medicalHistory.blood_group || 'N/A'}`, 20, 73);
    
    doc.text(`Emergency Contact: ${medicalHistory.emergency_contact || 'N/A'}`, 20, 85);
    
    doc.setFont("helvetica", "bold");
    doc.text("Medical History", 20, 100);
    doc.setFont("helvetica", "normal");
    doc.text(`Known Allergies: ${medicalHistory.known_allergies || 'None'}`, 20, 110);
    doc.text(`Chronic Diseases: ${medicalHistory.chronic_diseases || 'None'}`, 20, 117);
    
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Disclaimer: This report is auto-generated by MediAssist AI. It is not a formal", 20, 270);
    doc.text("medical diagnosis. Please consult a healthcare professional for accurate medical advice.", 20, 275);
    
    doc.save(`${user?.name?.replace(' ', '_')}_Health_Report.pdf`);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 animate-spin text-[#0EA5E9]" />
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto animate-in fade-in duration-300">
      <div className="bg-white dark:bg-slate-800 rounded-3xl shadow-sm border border-slate-100 dark:border-slate-700 overflow-hidden">
        
        <div className="bg-slate-50 dark:bg-slate-900/50 p-8 border-b border-slate-100 dark:border-slate-700 flex flex-col md:flex-row items-center gap-6 justify-between">
          <div className="flex items-center gap-6">
            <div className="w-24 h-24 bg-[#0EA5E9]/10 text-[#0EA5E9] rounded-full flex items-center justify-center">
              <User className="w-12 h-12" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-1">{user?.name}</h1>
              <p className="text-slate-500">{user?.email}</p>
            </div>
          </div>
          
          <button 
            onClick={generateReport}
            className="bg-slate-900 hover:bg-slate-800 dark:bg-slate-700 dark:hover:bg-slate-600 text-white px-4 py-2 rounded-xl flex items-center gap-2 transition-colors"
          >
            <FileText className="w-4 h-4" /> Generate PDF Report
          </button>
        </div>

        <div className="p-8">
          <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-slate-900 dark:text-white">
            <Activity className="text-[#22C55E]" /> Medical History
          </h2>

          {message.text && (
            <div className={`p-4 rounded-xl text-sm mb-6 ${message.type === 'success' ? 'bg-green-50 text-green-600' : 'bg-red-50 text-red-600'}`}>
              {message.text}
            </div>
          )}

          <form onSubmit={handleSave} className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Age</label>
              <input
                type="number"
                className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-700 focus:ring-2 focus:ring-[#0EA5E9] outline-none dark:text-white"
                value={medicalHistory.age}
                onChange={(e) => setMedicalHistory({...medicalHistory, age: e.target.value})}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Gender</label>
              <select
                className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-700 focus:ring-2 focus:ring-[#0EA5E9] outline-none dark:text-white"
                value={medicalHistory.gender}
                onChange={(e) => setMedicalHistory({...medicalHistory, gender: e.target.value})}
              >
                <option value="">Select...</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
                <option value="Prefer not to say">Prefer not to say</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Blood Group</label>
              <select
                className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-700 focus:ring-2 focus:ring-[#0EA5E9] outline-none dark:text-white"
                value={medicalHistory.blood_group}
                onChange={(e) => setMedicalHistory({...medicalHistory, blood_group: e.target.value})}
              >
                <option value="">Select...</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Emergency Contact</label>
              <input
                type="text"
                placeholder="+1 234 567 890"
                className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-700 focus:ring-2 focus:ring-[#0EA5E9] outline-none dark:text-white"
                value={medicalHistory.emergency_contact}
                onChange={(e) => setMedicalHistory({...medicalHistory, emergency_contact: e.target.value})}
              />
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Known Allergies (comma separated)</label>
              <input
                type="text"
                placeholder="Peanuts, Penicillin..."
                className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-700 focus:ring-2 focus:ring-[#0EA5E9] outline-none dark:text-white"
                value={medicalHistory.known_allergies}
                onChange={(e) => setMedicalHistory({...medicalHistory, known_allergies: e.target.value})}
              />
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Chronic Diseases (comma separated)</label>
              <input
                type="text"
                placeholder="Asthma, Diabetes..."
                className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-700 focus:ring-2 focus:ring-[#0EA5E9] outline-none dark:text-white"
                value={medicalHistory.chronic_diseases}
                onChange={(e) => setMedicalHistory({...medicalHistory, chronic_diseases: e.target.value})}
              />
            </div>

            <div className="md:col-span-2 flex justify-end mt-4">
              <button
                type="submit"
                disabled={saving}
                className="bg-[#0EA5E9] hover:bg-[#0284c7] text-white px-6 py-3 rounded-xl font-medium transition-colors flex items-center gap-2 disabled:opacity-50"
              >
                {saving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save className="w-5 h-5" />}
                Save Changes
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Profile;
